version: '3'
services:
  nginx:
    image: 'nginx:stable'
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/
      - ~/nginx/sites-enabled/:/etc/nginx/sites-enabled/ # Sync config from host
    networks:
      - sail
  app:
    build:
      args:
        user: root
        uid: 1000
      context: ./
      dockerfile: docker_configs/php/Dockerfile
    restart: unless-stopped

    ports:
      - '9000:9000'
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./php.conf:/usr/local/etc/php8.1-fpm.d/php.conf
      - ./storage/logs/php-error.log:/var/log/error.log
      - ./storage/logs/php-access.log:/var/log/access.log
    networks:
      - sail
    depends_on:
      - mysql
  #            - pgsql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
