version: '3'
services:
  nginx:
    image: 'nginx:stable'
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/
      - ./docker_configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Sync config from host
    networks:
      - kpm
    depends_on:
      - app
  app:
    build:
      context: ./
      dockerfile: docker_configs/php/Dockerfile
    restart: unless-stopped
    ports:
      - '9000:9000'
    working_dir: /var/www
    volumes:
      - ./docker_configs/php/php.ini:/usr/local/etc/php/conf.d/app.ini
      - ./:/var/www
    networks:
      - kpm
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mysql-db:/var/lib/mysql'
    networks:
      - kpm

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-db:/data
    networks:
      - kpm
networks:
  kpm:
    driver: bridge
volumes:
  mysql-db:
    driver: local
  redis-db:
    driver: local
