on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Run ssh script
        run: echo '123'
      # with:
      #   key: ${{ secrets.SSH_PRIVATE_KEY }}

