on:
  push:
    branches:
      - main

jobs:
  my_job:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/laravel-ecommerce-shop
            git checkout .
            git pull origin main
            docker exec laravel-ecommerce-shop-app-1 yarn install
            docker exec laravel-ecommerce-shop-app-1 yarn build
            docker exec laravel-ecommerce-shop-app-1 php artisan optimize
            docker exec laravel-ecommerce-shop-app-1 php artisan route:cache
            docker exec laravel-ecommerce-shop-app-1 php artisan config:cache
            docker exec laravel-ecommerce-shop-app-1 php artisan view:cache
