on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Hello, remote server!"
            mkdir hehe
      # with:
      #   key: ${{ secrets.SSH_PRIVATE_KEY }}

